apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/sagemoonsamy/zntwk-tax_calculator"
        - name: revision
          value: "main"
    - name: build-app
      taskRef:
        name: tax-calculator-build-task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace